#ifndef grm

typedef int liczba_staloprzecinkowa;
typedef float liczba_zmiennoprzecinkowa; 

#define zwroc return
#define wypisz std::cout
#define dla for
#define rowna =
#define plus +
#define minus -
#define razy *
#define mniejsze <
#define wieksze >
#define dodaj_jeden ++
#define zakoncz ;
#define nastepna_linia "\n"
#define to <<
#define zero 0
#define jeden 1
#define dwa 2
#define trzy 3
#define cztery 4
#define piec 5
#define szesc 6
#define siedem 7
#define osiem 8
#define dziewiec 9
#define dziesiec 10
#define jedenascie 11
#define dwanascie 12
#define trzynascie 13
#define czternascie 14
#define pietnascie 15
#define szesnascie 16
#define siedemnascie 17
#define osiemnascie 18
#define dziewietnascie 19
#define dwadziescia 20
#define dwadziescia_jeden 21
#define dwadziescia_dwa 22
#define dwadziescia_trzy 23
#define dwadziescia_cztery 24
#define dwadziescia_piec 25
#define dwadziescia_szesc 26
#define dwadziescia_siedem 27
#define dwadziescia_osiem 28
#define dwadziescia_dziewiec 29
#define trzydziesci 30
#define trzydziesci_jeden 31
#define trzydziesci_dwa 32
#define trzydziesci_trzy 33
#define trzydziesci_cztery 34
#define trzydziesci_piec 35
#define trzydziesci_szesc 36
#define trzydziesci_siedem 37
#define trzydziesci_osiem 38
#define trzydziesci_dziewiec 39
#define czterdziesci 40
#define czterdziesci_jeden 41
#define czterdziesci_dwa 42
#define czterdziesci_trzy 43
#define czterdziesci_cztery 44
#define czterdziesci_piec 45
#define czterdziesci_szesc 46
#define czterdziesci_siedem 47
#define czterdziesci_osiem 48
#define czterdziesci_dziewiec 49
#define piecdziesiat 50
#define piecdziesiat_jeden 51
#define piecdziesiat_dwa 52
#define piecdziesiat_trzy 53
#define piecdziesiat_cztery 54
#define piecdziesiat_piec 55
#define piecdziesiat_szesc 56
#define piecdziesiat_siedem 57
#define piecdziesiat_osiem 58
#define piecdziesiat_dziewiec 59
#define szescdziesiat 60
#define szescdziesiat_jeden 61
#define szescdziesiat_dwa 62
#define szescdziesiat_trzy 63
#define szescdziesiat_cztery 64
#define szescdziesiat_piec 65
#define szescdziesiat_szesc 66
#define szescdziesiat_siedem 67
#define szescdziesiat_osiem 68
#define szescdziesiat_dziewiec 69
#define siedemdziesiat 70
#define siedemdziesiat_jeden 71
#define siedemdziesiat_dwa 72
#define siedemdziesiat_trzy 73
#define siedemdziesiat_cztery 74
#define siedemdziesiat_piec 75
#define siedemdziesiat_szesc 76
#define siedemdziesiat_siedem 77
#define siedemdziesiat_osiem 78
#define siedemdziesiat_dziewiec 79
#define osiemdziesiat 80
#define osiemdziesiat_jeden 81
#define osiemdziesiat_dwa 82
#define osiemdziesiat_trzy 83
#define osiemdziesiat_cztery 84
#define osiemdziesiat_piec 85
#define osiemdziesiat_szesc 86
#define osiemdziesiat_siedem 87
#define osiemdziesiat_osiem 88
#define osiemdziesiat_dziewiec 89
#define dziewiecdziesiat 90
#define dziewiecdziesiat_jeden 91
#define dziewiecdziesiat_dwa 92
#define dziewiecdziesiat_trzy 93
#define dziewiecdziesiat_cztery 94
#define dziewiecdziesiat_piec 95
#define dziewiecdziesiat_szesc 96
#define dziewiecdziesiat_siedem 97
#define dziewiecdziesiat_osiem 98
#define dziewiecdziesiat_dziewiec 99
#define sto 100

#endif